import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
const out = 'delivery/physical-interactions';
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--enable-unsafe-swiftshader'] });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  await page.clock.install();
  await page.clock.pauseAt(new Date());
  const errors = [], external = [];
  page.on('pageerror', error => errors.push(String(error)));
  await page.route('**/*', route => {
    if (!route.request().url().startsWith('http://127.0.0.1:5207/')) { external.push(route.request().url()); return route.abort(); }
    return route.continue();
  });
  await page.goto('http://127.0.0.1:5207/?source=firebase');
  await page.locator('.sompo-simulator-canvas canvas').waitFor();
  await page.clock.runFor(100);
  const send = raw => page.evaluate(raw => window.__sompoPreview.setPhysicalReading(raw), raw);
  const severity = () => page.locator('.sompo-physical-hud').getAttribute('data-severity');
  await send({ timestamp: 1000 }); await page.clock.runFor(250);
  assert.equal(await severity(), 'clear');
  await send({ timestamp: 1200, distancia: 150 }); await page.clock.runFor(250);
  assert.equal(await severity(), 'attention');
  await send({ timestamp: 1400, distancia: 35, riscoColisao: true, pitch: 26, aceleracaoX: 18 });
  await page.clock.runFor(400);
  assert.equal(await severity(), 'danger');
  await page.screenshot({ path: `${out}/proximity-tilt-desktop.png`, fullPage: true });
  await send({ timestamp: 1600, temperatura: 40, umidade: 88 }); await page.clock.runFor(300);
  await page.getByRole('button', { name: 'Ver carga em 3D', exact: true }).click();
  await page.clock.runFor(100);
  assert.equal(await page.evaluate(() => window.__sompoPreview.scene.getObjectByName('sompo-physical-cargo').visible), true);
  await page.screenshot({ path: `${out}/cargo-environment.png`, fullPage: true });
  await send({ timestamp: 1800, distancia: 999 }); await page.clock.runFor(300);
  assert.match(await page.locator('.sompo-physical-hud').innerText(), /sem eco válido/);
  assert.equal(await page.evaluate(() => window.__sompoPreview.scene.getObjectByName('sompo-physical-proximity').children[0].visible), false);
  await send({ timestamp: 2000 });
  await page.clock.fastForward(4500);
  await page.locator('.sompo-physical-events button').first().waitFor({ timeout: 8000 });
  await page.locator('.sompo-physical-events button').first().click();
  assert.match(await page.locator('.sompo-physical-hud').innerText(), /REPLAY/);
  await page.getByRole('button', { name: 'Pausar replay', exact: true }).click();
  const progress = await page.locator('.sompo-physical-replay progress').getAttribute('value');
  await send({ timestamp: 2200, distancia: 10, riscoColisao: true }); await page.clock.runFor(300);
  assert.equal(await page.locator('.sompo-physical-replay progress').getAttribute('value'), progress);
  assert.notEqual(await severity(), 'danger', 'incoming live data must not replace paused replay');
  await page.screenshot({ path: `${out}/replay.png`, fullPage: true });
  await page.getByRole('button', { name: 'Voltar ao vivo', exact: true }).click();
  await page.clock.runFor(300); assert.equal(await severity(), 'danger');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.clock.runFor(300);
  assert.equal(await page.locator('.sompo-physical-vignette').evaluate(element => getComputedStyle(element).animationName), 'none');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile overflow');
  await page.screenshot({ path: `${out}/mobile-reduced-motion.png`, fullPage: true });
  await page.clock.fastForward(15500);
  await page.clock.runFor(100);
  assert.equal(await severity(), 'offline');
  assert.equal(await page.evaluate(() => window.__sompoPreview.samples.length), 0, 'physical mode must never post synthetic data');
  assert.equal(await page.locator('canvas').count(), 1);
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
  writeFileSync(`${out}/results.json`, JSON.stringify({ ok: true, errors, external, checks: ['proximity', 'inclination', 'cargo', 'invalid echo', 'event capture', 'replay pause and live isolation', 'return live', 'mobile', 'reduced motion', 'stale feed', 'zero writes'] }, null, 2));
  console.log('Physical twin: all browser checks passed');
} finally { await browser.close(); }
