import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { cli, runtime, temporary } from './support/cli.js';

test('CLI operates the real isolated runtime: sessions, CRUD, files, sharing, schedules, lab and support', { timeout: 60000 }, async t => {
  const directory = await temporary(t);
  const url = await runtime(t, directory);
  const config = path.join(directory, 'cli.json');
  const env = { LUCA_URL: url, LUCA_CLI_CONFIG: config };
  async function ok(args, profile = 'admin', input = '') {
    const result = await cli([...args, '--profile', profile], { env, input });
    assert.equal(result.code, 0, `${args.join(' ')}: ${result.stderr}`);
    return result.json;
  }
  assert.equal((await cli(['state'], { env })).code, 3);
  const admin = await ok(['auth', 'register', '--name', 'Admin CLI', '--email', 'admin@cli.test', '--password-stdin'], 'admin', 'cli-test-password-123\n');
  assert.equal(admin.user.role, 'admin');
  const user = await ok(['auth', 'register', '--name', 'Cliente CLI', '--email', 'user@cli.test', '--password-stdin'], 'user', 'cli-test-password-456\n');
  assert.equal(user.user.role, 'user');
  assert.equal((await ok(['auth', 'session'])).user.id, admin.user.id);
  assert.equal((await cli(['admin', 'users', 'list', '--profile', 'user'], { env })).code, 3);
  assert.ok((await ok(['models'])).routeIds.length > 0);
  const template = (await ok(['templates', 'create', '--kind', 'individual', '--template', '{"label":"Revisores CLI","participants":["arquiteto"],"judge":"revisor"}'])).template;
  await ok(['templates', 'update', 'individual', template.id, '--template', JSON.stringify({ ...template, label: 'Revisores atualizados' })]);
  const templates = await ok(['templates', 'list']);
  const templateList = templates.individual;
  assert.ok(templateList.some(item => item.id === template.id && item.label === 'Revisores atualizados'));
  await ok(['templates', 'reorder', 'individual', '--ids', templateList.map(item => item.id).reverse().join(',')]);
  await ok(['templates', 'delete', 'individual', template.id]);
  const folder = (await ok(['chat', 'folders', 'create', '--name', 'Testes CLI'])).folder;
  const session = (await ok(['chat', 'sessions', 'create', '--title', 'Análise de campo', '--folder-id', folder.id, '--no-seed-from-active'])).session;
  assert.equal((await ok(['chat', 'sessions', 'get', session.id])).session.title, 'Análise de campo');
  assert.equal((await cli(['chat', 'sessions', 'get', session.id, '--profile', 'user'], { env })).code, 1);
  await ok(['chat', 'sessions', 'update', session.id, '--title', 'Análise atualizada', '--folder-id', 'null']);
  assert.equal((await ok(['chat', 'sessions', 'get', session.id])).session.folderId, null);
  const file = path.join(directory, 'evidência.txt');
  const bytes = Buffer.from('Um arquivo de evidência.\nOutra linha.\n');
  await fs.writeFile(file, bytes);
  const attachment = (await ok(['chat', 'attachments', 'upload', session.id, '--file', file])).attachment;
  const downloaded = path.join(directory, 'download.txt');
  await ok(['chat', 'attachments', 'get', session.id, attachment.id, '--output', downloaded]);
  assert.deepEqual(await fs.readFile(downloaded), bytes);
  assert.equal((await cli(['chat', 'attachments', 'get', session.id, attachment.id, '--profile', 'user', '--output', path.join(directory, 'forbidden.txt')], { env })).code, 1);
  await ok(['chat', 'attachments', 'delete', session.id, attachment.id]);
  const shared = (await ok(['chat', 'share', 'create', session.id])).share;
  assert.ok(shared);
  const share = await ok(['chat', 'share', 'get', session.id]);
  assert.ok(share.share);
  await ok(['chat', 'share', 'revoke', session.id]);
  assert.equal((await ok(['chat', 'share', 'get', session.id])).share, null);
  await ok(['chat', 'folders', 'rename', folder.id, '--name', 'Verificado']);
  await ok(['chat', 'folders', 'delete', folder.id]);
  const schedule = (await ok(['schedule', 'create', '--description', 'Teste futuro', '--interval-value', '1', '--interval-unit', 'days', '--total-runs', '2'])).schedule;
  await ok(['schedule', 'pause', schedule.id, '--reason', 'Verificação CLI']);
  assert.ok((await ok(['schedule', 'list'])).scheduledMissions.find(item => item.id === schedule.id).pausedAt);
  await ok(['schedule', 'resume', schedule.id]);
  await ok(['schedule', 'cancel', schedule.id]);
  const labCase = (await ok(['lab', 'cases', 'import', '--csv', 'datasets/laboratorio-virtual-v1/01-operacao-normal.csv', '--name', 'Caso CLI'])).case;
  assert.ok(labCase.sampleCount > 0);
  const conclusion = await ok(['lab', 'cases', 'conclude', labCase.id, '--observations', 'Dados do ensaio sintético. <script>unsafe()</script>', '--category', 'inconclusive', '--action', 'Revisar evidências adicionais.']);
  assert.equal(conclusion.conclusion.version, 1);
  assert.equal((await ok(['lab', 'cases', 'get', labCase.id])).case.conclusions.length, 1);
  const savedCase = path.join(directory, 'case.json');
  await ok(['lab', 'cases', 'get', labCase.id, '--output', savedCase]);
  const report = path.join(directory, 'report.html');
  await ok(['lab', 'report', '--data', `@${savedCase}`, '--author', 'Agente CLI', '--output', report]);
  const html = await fs.readFile(report, 'utf8');
  assert.match(html, /Dados do ensaio sintético/);
  assert.match(html, /Agente CLI/);
  assert.ok(!html.includes('<script>unsafe()'));
  assert.match(html, /&lt;script&gt;unsafe\(\)&lt;\/script&gt;/);
  assert.equal((await ok(['lab', 'cases', 'list'], 'user')).cases.length, 0);
  const episode = (await ok(['sompo', 'episodes', 'start', '--kind', 'roteiro', '--scenario-id', 'normal', '--scenario-label', 'CLI', '--trator', 'SIM-001'])).episode;
  assert.ok(episode.publicId);
  const samples = [];
  for (const time of [0, 1000]) {
    const simulated = await ok(['sompo', 'simulate', '--scenario', 'normal', '--elapsed-ms', String(time), '--data', JSON.stringify({ observedAt: new Date(Date.now() + time).toISOString() })]);
    samples.push(...simulated.samples);
  }
  await ok(['sompo', 'simulation', 'record', '--data', JSON.stringify({ samples, episodeId: episode.publicId })]);
  await ok(['sompo', 'episodes', 'get', episode.publicId]);
  const exported = path.join(directory, 'sompo.csv');
  await ok(['sompo', 'export', '--episode-id', episode.publicId, '--format', 'csv', '--output', exported]);
  assert.ok((await ok(['lab', 'inspect', '--csv', exported])).case.samples.length >= 2);
  const dataset = path.join(directory, 'sompo.json');
  await ok(['sompo', 'export', '--episode-id', episode.publicId, '--output', dataset]);
  const converted = path.join(directory, 'converted.csv');
  await ok(['lab', 'convert', '--data', `@${dataset}`, '--output', converted]);
  assert.deepEqual(await fs.readFile(converted), await fs.readFile(exported));
  await ok(['sompo', 'episodes', 'finish', episode.publicId, '--status', 'aborted']);
  const deliberation = await cli(['deliberations', 'create', '--objective', 'Teste offline', '--team', '{"mode":"parallel","slugs":["missing-persona"]}', '--wait', '--interval', '100', '--wait-timeout', '5000'], { env: { ...env, LUCA_MACHINE_TOKEN: 'cli-test-machine-token-local-only-123456789' } });
  assert.equal(deliberation.code, 5, deliberation.stderr);
  assert.match(deliberation.stderr, /deliberationId/);
  await ok(['admin', 'users', 'impersonate', user.user.id]);
  assert.equal((await ok(['auth', 'session'])).user.id, user.user.id);
  await ok(['auth', 'stop-impersonation']);
  assert.equal((await ok(['auth', 'session'])).user.id, admin.user.id);
  await ok(['chat', 'sessions', 'delete', session.id]);
  await ok(['auth', 'logout']);
  assert.equal((await ok(['auth', 'session'])).user, null);
  assert.equal((await cli(['state', '--profile', 'admin'], { env })).code, 3);
  await ok(['auth', 'login', '--email', 'admin@cli.test', '--password-stdin'], 'admin', 'cli-test-password-123\n');
  assert.equal((await ok(['auth', 'session'])).user.id, admin.user.id);
});
