function schema(type, properties = {}, required = []) {
  const shape = { type, properties };
  if (required.length > 0) shape.required = required;
  return shape;
}

function tool(spec) {
  return spec;
}

export function buildToolCatalog({ mode = 'backend' } = {}) {
  const runtime = mode === 'cloud' ? 'cloud' : 'local';
  const tools = [
    tool({
      id: 'mission_activate',
      name: 'Ativar Missao',
      description: 'Abre uma missao nova no runtime LUCA com briefing e criterio de sucesso.',
      category: 'missao',
      kind: 'action',
      provider: 'luca',
      capabilities: ['orquestracao', 'briefing', 'run'],
      tags: ['mission', 'supervisor', 'runtime'],
      prompt_instruction: 'Use para iniciar uma nova rodada operacional quando houver objetivo claro e criterio de entrega.',
      parameters: schema('object', {
        title: { type: 'string', description: 'titulo curto da missao' },
        description: { type: 'string', description: 'briefing operacional' },
        success: { type: 'string', description: 'definicao de sucesso esperada' },
      }, ['description']),
      invoke: { type: 'http', method: 'POST', endpoint: '/api/mission/activate' },
      executable: true,
      availability: 'both',
      source: 'tars-tool-catalog-pattern',
    }),
    tool({
      id: 'mission_signal',
      name: 'Injetar Sinal',
      description: 'Empurra um sinal em tempo real para a missao ativa, influenciando a proxima rodada do supervisor.',
      category: 'missao',
      kind: 'action',
      provider: 'luca',
      capabilities: ['telemetria', 'tempo-real', 'contexto'],
      tags: ['signal', 'realtime', 'mission'],
      prompt_instruction: 'Use para anexar fatos novos ou alertas durante uma missao em curso.',
      parameters: schema('object', {
        title: { type: 'string', description: 'nome curto do sinal' },
        detail: { type: 'string', description: 'conteudo operacional do sinal' },
        severity: { type: 'string', enum: ['low', 'medium', 'high', 'critical'], description: 'grau de severidade' },
        source: { type: 'string', description: 'origem do sinal' },
      }, ['title', 'detail']),
      invoke: { type: 'http', method: 'POST', endpoint: '/api/mission/signal' },
      executable: true,
      availability: 'local',
      source: 'tars-tool-catalog-pattern',
    }),
    tool({
      id: 'agent_run',
      name: 'Executar Agente',
      description: 'Dispara um agente ou persona importada para contribuir com a missao ativa.',
      category: 'agentes',
      kind: 'action',
      provider: 'luca',
      capabilities: ['agent', 'persona', 'execucao-manual'],
      tags: ['agent', 'persona', 'manual'],
      prompt_instruction: 'Use para forcar uma contribuicao de um agente especifico sem esperar o proximo ciclo automatico.',
      parameters: schema('object', {
        agentId: { type: 'string', description: 'id do agente builtin ou persona importada' },
      }, ['agentId']),
      invoke: { type: 'http', method: 'POST', endpoint: '/api/agent/run' },
      executable: true,
      availability: 'local',
      source: 'tars-tool-catalog-pattern',
    }),
    tool({
      id: 'heartbeat_control',
      name: 'Controle de Heartbeat',
      description: 'Liga ou pausa o monitor de heartbeat do runtime atual.',
      category: 'runtime',
      kind: 'action',
      provider: 'luca',
      capabilities: ['heartbeat', 'monitoramento', 'runtime'],
      tags: ['heartbeat', 'monitor'],
      prompt_instruction: 'Use para controlar a observabilidade de pulso do sistema.',
      parameters: schema('object', {
        action: { type: 'string', enum: ['start', 'pause'], description: 'acao desejada sobre o heartbeat' },
      }, ['action']),
      invoke: {
        type: 'http-multi',
        endpoints: {
          start: '/api/heartbeat/start',
          pause: '/api/heartbeat/pause',
        },
      },
      executable: true,
      availability: 'both',
      source: 'tars-tool-catalog-pattern',
    }),
    tool({
      id: 'runtime_preflight',
      name: 'Preflight Operacional',
      description: 'Executa uma checagem rápida de readiness antes de missão live, validando endpoints críticos e lock de concorrência.',
      category: 'runtime',
      kind: 'catalog',
      provider: 'luca',
      capabilities: ['preflight', 'health', 'readiness'],
      tags: ['preflight', 'health', 'mission'],
      prompt_instruction: 'Use antes de abrir missão viva ou acionar GLM quando precisar confirmar que health, state, events e governança estão coerentes.',
      parameters: schema('object'),
      invoke: { type: 'http', method: 'GET', endpoint: '/api/preflight' },
      executable: true,
      availability: 'local',
      source: 'kamui-service-health-pattern',
    }),
    tool({
      id: 'event_summary',
      name: 'Resumo de Eventos',
      description: 'Consolida o feed persistido de eventos em um resumo operacional com latest, contagens por tipo e origem.',
      category: 'runtime',
      kind: 'catalog',
      provider: 'luca',
      capabilities: ['observability', 'events', 'reporting'],
      tags: ['events', 'summary', 'trace'],
      prompt_instruction: 'Use para validar rapidamente o estado operacional recente ou inspecionar um missionId/traceId sem percorrer o feed bruto inteiro.',
      parameters: schema('object', {
        type: { type: 'string', description: 'filtro opcional por tipo de evento' },
        missionId: { type: 'string', description: 'filtro opcional por missao' },
        goalId: { type: 'string', description: 'filtro opcional por goal' },
        traceId: { type: 'string', description: 'filtro opcional por trilha correlacionada' },
        limit: { type: 'integer', description: 'janela amostral maxima usada no resumo' },
      }),
      invoke: { type: 'http', method: 'GET', endpoint: '/api/events/summary' },
      executable: true,
      availability: 'both',
      source: 'tars-event-summary-pattern',
    }),
    tool({
      id: 'governance_catalog',
      name: 'Consultar Governanca',
      description: 'Lê a politica operacional do runtime cloud, incluindo budgets padrao e alerta de missao concorrente.',
      category: 'runtime',
      kind: 'catalog',
      provider: 'luca',
      capabilities: ['governance', 'policy', 'runtime'],
      tags: ['governance', 'policy', 'tars'],
      prompt_instruction: 'Use antes de mutar producao ou abrir missao live para checar budgets, bloqueios e concorrencia recente.',
      parameters: schema('object'),
      invoke: { type: 'http', method: 'GET', endpoint: '/api/governance' },
      executable: true,
      availability: 'cloud',
      source: 'tars-governance-pattern',
    }),
    tool({
      id: 'schedule_control',
      name: 'Controle de Agenda',
      description: 'Cria ou altera agendamentos recorrentes de missao sem acessar o estado bruto manualmente.',
      category: 'agenda',
      kind: 'action',
      provider: 'luca',
      capabilities: ['schedule', 'queue', 'recorrencia'],
      tags: ['schedule', 'queue'],
      prompt_instruction: 'Use para operar a fila recorrente de missoes e ajustar cadencia.',
      parameters: schema('object', {
        mode: { type: 'string', enum: ['create', 'pause', 'resume', 'cancel'], description: 'operacao de agenda' },
        scheduleId: { type: 'string', description: 'id do agendamento quando aplicavel' },
        description: { type: 'string', description: 'descricao da missao quando mode=create' },
        intervalValue: { type: 'integer', description: 'valor do intervalo quando mode=create' },
        intervalUnit: { type: 'string', enum: ['minutes', 'hours', 'days'], description: 'unidade do intervalo' },
      }, ['mode']),
      invoke: {
        type: 'http-multi',
        endpoints: {
          create: '/api/mission/schedule',
          pause: '/api/schedule/pause',
          resume: '/api/schedule/resume',
          cancel: '/api/schedule/cancel',
        },
      },
      executable: true,
      availability: 'local',
      source: 'tars-tool-catalog-pattern',
    }),
    tool({
      id: 'global_chat_message',
      name: 'Mensagem no Chat Global',
      description: 'Publica uma mensagem manual no chat global do LUCA para orientar operadores e agentes.',
      category: 'comms',
      kind: 'action',
      provider: 'luca',
      capabilities: ['chat', 'coordenação', 'operacao'],
      tags: ['chat', 'broadcast'],
      prompt_instruction: 'Use para registrar uma orientacao curta ou observacao operacional no chat global.',
      parameters: schema('object', {
        content: { type: 'string', description: 'mensagem a publicar' },
        type: { type: 'string', enum: ['info', 'resultado', 'decisao', 'pergunta', 'alerta', 'acao', 'sistema'], description: 'classificacao da mensagem' },
        agentId: { type: 'string', description: 'autor logico da mensagem' },
      }, ['content']),
      invoke: { type: 'http', method: 'POST', endpoint: '/api/tools/global-chat/message' },
      executable: true,
      availability: 'local',
      source: 'tars-tool-catalog-pattern',
    }),
    tool({
      id: 'persona_catalog',
      name: 'Catalogo de Personas',
      description: 'Consulta o catalogo de personas disponiveis no Yume para importacao segura no LUCA.',
      category: 'pontes',
      kind: 'bridge',
      provider: 'kamui+yume',
      capabilities: ['persona', 'bridge', 'discovery'],
      tags: ['yume', 'personas', 'catalog'],
      prompt_instruction: 'Use antes de importar especialistas do Yume para confirmar disponibilidade e metadados.',
      parameters: schema('object'),
      invoke: { type: 'http', method: 'GET', endpoint: '/api/personas/available' },
      executable: runtime === 'local',
      availability: 'local',
      source: 'tars-tool-catalog-pattern',
    }),
    tool({
      id: 'yume_memory_event_preview',
      name: 'Preview Memoria Yume',
      description: 'Gera um payload MemoryEventIn a partir do relatorio e evidencias da missao atual ou arquivada.',
      category: 'pontes',
      kind: 'bridge',
      provider: 'luca+yume',
      capabilities: ['memory', 'evidence', 'reporting', 'bridge'],
      tags: ['yume', 'memory', 'evidence'],
      prompt_instruction: 'Use antes de sincronizar conhecimento de uma missao LUCA no Yume; revise o payload e evite enviar transcript bruto.',
      parameters: schema('object', {
        missionId: { type: 'string', description: 'id opcional da missao arquivada; vazio usa a missao ativa quando existir' },
      }),
      invoke: { type: 'http', method: 'GET', endpoint: '/api/integrations/yume/memory-event' },
      executable: true,
      availability: 'local',
      source: 'yume-hybrid-memory-contract',
    }),
    tool({
      id: 'goal_create',
      name: 'Criar Goal',
      description: 'Registra um objetivo persistido no runtime cloud com definition of done e limites operacionais.',
      category: 'goals',
      kind: 'action',
      provider: 'luca',
      capabilities: ['goal', 'budget', 'planning'],
      tags: ['goal', 'runtime', 'tars'],
      prompt_instruction: 'Use para abrir uma trilha de trabalho persistida e rastreavel sem disparar uma missao viva.',
      parameters: schema('object', {
        title: { type: 'string', description: 'nome curto do objetivo' },
        description: { type: 'string', description: 'contexto operacional do objetivo' },
        definitionOfDone: { type: 'string', description: 'critério de saída objetivo' },
        priority: { type: 'integer', description: 'prioridade de 1 a 9' },
        maxIterations: { type: 'integer', description: 'limite de iterações' },
        maxSeconds: { type: 'integer', description: 'limite de tempo em segundos' },
        maxToolCalls: { type: 'integer', description: 'limite de chamadas operacionais' },
      }, ['title']),
      invoke: { type: 'http', method: 'POST', endpoint: '/api/goals' },
      executable: runtime === 'cloud',
      availability: 'cloud',
      source: 'tars-goals-pattern',
    }),
    tool({
      id: 'goal_catalog',
      name: 'Consultar Goals',
      description: 'Consulta a fila de goals persistidos no runtime cloud e seus budgets/status.',
      category: 'goals',
      kind: 'catalog',
      provider: 'luca',
      capabilities: ['goal', 'status', 'discovery'],
      tags: ['goal', 'catalog', 'runtime'],
      prompt_instruction: 'Use para revisar objetivos abertos, executando ou concluídos sem abrir o estado bruto.',
      parameters: schema('object', {
        status: { type: 'string', description: 'filtro opcional por status do goal' },
      }),
      invoke: { type: 'http', method: 'GET', endpoint: '/api/goals' },
      executable: true,
      availability: 'cloud',
      source: 'tars-goals-pattern',
    }),
    tool({
      id: 'endpoint_catalog',
      name: 'Catalogo de Endpoints',
      description: 'Entrega o contrato navegavel das rotas operacionais do LUCA, espelhando o estilo de mapeamento do TARS.',
      category: 'docs',
      kind: 'catalog',
      provider: 'luca',
      capabilities: ['docs', 'contract', 'discovery'],
      tags: ['catalog', 'endpoints'],
      prompt_instruction: 'Use para consultar rapidamente o que o runtime expõe e o que ele aceita receber.',
      parameters: schema('object'),
      invoke: { type: 'http', method: 'GET', endpoint: '/api/catalog/endpoints' },
      executable: true,
      availability: 'both',
      source: 'tars-tool-catalog-pattern',
    }),
    tool({
      id: 'catalog_audit',
      name: 'Auditar Catalogos',
      description: 'Valida o contrato entre catalogo de endpoints e catalogo de ferramentas, incluindo metodos, payloads e invokes.',
      category: 'docs',
      kind: 'catalog',
      provider: 'luca',
      capabilities: ['catalog', 'contract', 'quality-gate'],
      tags: ['catalog', 'audit', 'endpoints', 'tools'],
      prompt_instruction: 'Use antes de expor novas ferramentas ou rotas para confirmar que o catalogo esta coerente e navegavel.',
      parameters: schema('object'),
      invoke: { type: 'http', method: 'GET', endpoint: '/api/catalog/audit' },
      executable: true,
      availability: 'both',
      source: 'kamui-catalog-audit-pattern',
    }),
  ].filter((entry) => entry.availability === 'both' || entry.availability === runtime);

  return {
    generatedAt: new Date().toISOString(),
    mode,
    source: 'tars-tool-catalog-pattern',
    tools,
    count: tools.length,
  };
}
