import { chromium } from 'playwright';
const port = process.env.SHOT_PORT || '5201';
const pitch = process.env.SHOT_PITCH || '10';
const name = process.env.SHOT_NAME || `pitch${pitch}`;
const browser = await chromium.launch({ headless: true, executablePath: '/opt/google/chrome/chrome', args: ['--use-angle=gl', '--enable-gpu', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => console.error('PAGE', String(e).slice(0, 600)));
await page.goto(`http://127.0.0.1:${port}/?benchmark=1&offscreen=1`);
await page.waitForFunction(() => document.querySelector('[data-sompo-simulator]')?.dataset.sompoModel && document.querySelector('[data-sompo-simulator]').dataset.sompoModel !== 'loading', null, { timeout: 90000 });
await page.waitForTimeout(3000);
await page.locator('input[name="sompo-pitch"]').fill(pitch);
await page.evaluate(ms => window.__sompoPreview.advance(ms), 3000);
await page.waitForFunction(() => window.__sompoPreview.time === window.__sompoPreview.until, null, { timeout: 60000 });
await page.waitForTimeout(800);
await page.locator('[data-sompo-simulator]').screenshot({ path: `/tmp/sompo-look/shots/${name}.png` });
await browser.close();
console.log('done', name);
