import { chromium } from 'playwright';
const port = process.env.SHOT_PORT || '5197';
const scenario = process.env.SHOT_SCENARIO || 'agri-harvest-dust';
const browser = await chromium.launch({ headless: true, executablePath: '/opt/google/chrome/chrome', args: ['--use-angle=gl', '--enable-gpu', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => console.error('PAGE', String(e).slice(0, 400)));
await page.goto(`http://127.0.0.1:${port}/?benchmark=1&offscreen=1`);
await page.waitForFunction(() => document.querySelector('[data-sompo-simulator]')?.dataset.sompoModel && document.querySelector('[data-sompo-simulator]').dataset.sompoModel !== 'loading', null, { timeout: 90000 });
if (scenario !== 'default') await page.locator('select[name="sompo-scenario"]').selectOption(scenario);
await page.waitForTimeout(4000);
const out = await page.evaluate(() => {
  const p = window.__sompoPost;
  if (!p) return { err: 'sem __sompoPost' };
  const c = p.composer, r = c.renderer;
  const gl = r.getContext();
  const W = gl.drawingBufferWidth, H = gl.drawingBufferHeight;
  const px = new Uint8Array(4);
  const readScreen = (x, y) => { gl.bindFramebuffer(gl.FRAMEBUFFER, null); gl.readPixels(x, y, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, px); return [...px]; };
  const readRT = (rt, x, y) => { const buf = new Float32Array(4); try { r.readRenderTargetPixels(rt, x, y, 1, 1, buf); } catch (e) { return 'ERR ' + e.message; } return [...buf].map(v => +v.toFixed(3)); };
  const res = { W, H };
  c.render();
  res.screenAfterComposer = { mid: readScreen(W >> 1, H >> 1), top: readScreen(W >> 1, (H * 0.85) | 0) };
  res.readBufferMid = readRT(c.readBuffer, (W / 2) | 0, (H / 2) | 0);
  res.readBufferTop = readRT(c.readBuffer, (W / 2) | 0, (H * 0.85) | 0);
  return res;
});
console.log(scenario, JSON.stringify(out));
await browser.close();
