import { chromium } from 'playwright';
const port = process.env.SHOT_PORT || '5197';
const scenario = process.env.SHOT_SCENARIO || 'agri-harvest-dust';
const browser = await chromium.launch({ headless: true, executablePath: '/opt/google/chrome/chrome', args: ['--use-angle=gl', '--enable-gpu', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => console.error('PAGE', String(e).slice(0, 600)));
page.on('console', m => { const t = m.text(); if (!t.includes('404')) console.error(m.type().toUpperCase(), t.slice(0, 400)); });
await page.goto(`http://127.0.0.1:${port}/?benchmark=1&offscreen=1`);
await page.waitForFunction(() => document.querySelector('[data-sompo-simulator]')?.dataset.sompoModel && document.querySelector('[data-sompo-simulator]').dataset.sompoModel !== 'loading', null, { timeout: 90000 });
await page.locator('select[name="sompo-scenario"]').selectOption(scenario);
await page.waitForTimeout(6000);
await browser.close();
